require conf/machine/raspberrypi0-wifi.conf

MACHINEOVERRIDES =. "raspberrypi0-wifi:"

# Konsola szeregowa przez wbudowany CP2102 na HAT-cie
RPI_EXTRA_CONFIG += "\ndtoverlay=disable-bt\nenable_uart=1\n"
SERIAL_CONSOLES = "115200;ttyAMA0"

# USB host-mode pod HUB HAT (Waveshare, kabel micro-USB do portu OTG)
RPI_EXTRA_CONFIG += "\ndtoverlay=dwc2,dr_mode=host\n"
